### ISSUE TITLE
Feature: support IN and NIN comparison

### ISSUE THREAD

**Issue by mmueller90** [bitgrip/ficum#2]
Currently, the WITHIN comparison just works with the mongodbVisitor, it should be possible to implement this for the JpaPredicateVisitor, too.

The JPA CriteriaBuilder  has the possibility to use the IN statement for make an equals comparison with a list of values. (comaprable with the IN statement of sql)

**Comment by hschott** [comment]
WITHIN comparison is bound to geospatial analysis.
I think we should implement IN and NIN (NOT IN) as comparison for all supported storage engines.

**Comment by hschott** [comment]
Released with v0.8.0
